package com.web.service;

import java.util.List;

import com.web.model.Finance;

public interface FinanceService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int deleteByPrimaryKey(Integer financeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int insert(Finance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int insertSelective(Finance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    Finance selectByPrimaryKey(Integer financeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int updateByPrimaryKeySelective(Finance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int updateByPrimaryKey(Finance record);
    
    List<Finance> selAll();
    
    List<Finance> selectByFinanceName(String financeName);
}
