package com.web.service;

import java.util.List;

import com.web.model.Material;

public interface MaterialService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int deleteByPrimaryKey(Integer materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int insertSelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    Material selectByPrimaryKey(Integer materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int updateByPrimaryKeySelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    int updateByPrimaryKey(Material record);
    
    List<Material> selAll();
    
    List<Material> selectByMaterialName(String materialName);
}
