package com.web.service;

import java.util.List;

import com.web.model.ProjectProgress;

public interface ProjectProgressService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_progress
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    int deleteByPrimaryKey(Integer projectProgressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_progress
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    int insert(ProjectProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_progress
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    int insertSelective(ProjectProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_progress
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    ProjectProgress selectByPrimaryKey(Integer projectProgressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_progress
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_progress
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    int updateByPrimaryKey(ProjectProgress record);
    
    List<ProjectProgress> selAll();
    
    List<ProjectProgress> searchByPrimaryKey(Integer projectProgressId);
}
