package com.web.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Contract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_id
     *
     * @mbg.generated
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.party_a
     *
     * @mbg.generated
     */
    private String partyA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.party_b
     *
     * @mbg.generated
     */
    private String partyB;

    
    private String contractName;
   

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.start_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")    
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.end_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")  
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.total_days
     *
     * @mbg.generated
     */
    private Integer totalDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.quality_standard
     *
     * @mbg.generated
     */
    private String qualityStandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contracting_legal_person
     *
     * @mbg.generated
     */
    private String contractingLegalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contractual_legal_person
     *
     * @mbg.generated
     */
    private String contractualLegalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.sign_date
     *
     * @mbg.generated
     */
    private Date signDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_id
     *
     * @return the value of contract.contract_id
     *
     * @mbg.generated
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_id
     *
     * @param contractId the value for contract.contract_id
     *
     * @mbg.generated
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.party_a
     *
     * @return the value of contract.party_a
     *
     * @mbg.generated
     */
    public String getPartyA() {
        return partyA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.party_a
     *
     * @param partyA the value for contract.party_a
     *
     * @mbg.generated
     */
    public void setPartyA(String partyA) {
        this.partyA = partyA == null ? null : partyA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.party_b
     *
     * @return the value of contract.party_b
     *
     * @mbg.generated
     */
    public String getPartyB() {
        return partyB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.party_b
     *
     * @param partyB the value for contract.party_b
     *
     * @mbg.generated
     */
    
    public String getContractName() {
		return contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}
	
	
    public void setPartyB(String partyB) {
        this.partyB = partyB == null ? null : partyB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.start_time
     *
     * @return the value of contract.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.start_time
     *
     * @param startTime the value for contract.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.end_time
     *
     * @return the value of contract.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.end_time
     *
     * @param endTime the value for contract.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.total_days
     *
     * @return the value of contract.total_days
     *
     * @mbg.generated
     */
    public Integer getTotalDays() {
        return totalDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.total_days
     *
     * @param totalDays the value for contract.total_days
     *
     * @mbg.generated
     */
    public void setTotalDays(Integer totalDays) {
        this.totalDays = totalDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.quality_standard
     *
     * @return the value of contract.quality_standard
     *
     * @mbg.generated
     */
    public String getQualityStandard() {
        return qualityStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.quality_standard
     *
     * @param qualityStandard the value for contract.quality_standard
     *
     * @mbg.generated
     */
    public void setQualityStandard(String qualityStandard) {
        this.qualityStandard = qualityStandard == null ? null : qualityStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.price
     *
     * @return the value of contract.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.price
     *
     * @param price the value for contract.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contracting_legal_person
     *
     * @return the value of contract.contracting_legal_person
     *
     * @mbg.generated
     */
    public String getContractingLegalPerson() {
        return contractingLegalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contracting_legal_person
     *
     * @param contractingLegalPerson the value for contract.contracting_legal_person
     *
     * @mbg.generated
     */
    public void setContractingLegalPerson(String contractingLegalPerson) {
        this.contractingLegalPerson = contractingLegalPerson == null ? null : contractingLegalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contractual_legal_person
     *
     * @return the value of contract.contractual_legal_person
     *
     * @mbg.generated
     */
    public String getContractualLegalPerson() {
        return contractualLegalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contractual_legal_person
     *
     * @param contractualLegalPerson the value for contract.contractual_legal_person
     *
     * @mbg.generated
     */
    public void setContractualLegalPerson(String contractualLegalPerson) {
        this.contractualLegalPerson = contractualLegalPerson == null ? null : contractualLegalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.sign_date
     *
     * @return the value of contract.sign_date
     *
     * @mbg.generated
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.sign_date
     *
     * @param signDate the value for contract.sign_date
     *
     * @mbg.generated
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }
}