package com.web.model;


import java.util.Date;

public class Finance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.finance_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private Integer financeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.contract_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private Integer contractId;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.finance_name
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private String financeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.money
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.settleDate
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private Date settledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.remark
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.finance_id
     *
     * @return the value of finance.finance_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    
    private String contractName;
    
   

	public Integer getFinanceId() {
        return financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.finance_id
     *
     * @param financeId the value for finance.finance_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setFinanceId(Integer financeId) {
        this.financeId = financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.contract_id
     *
     * @return the value of finance.contract_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.contract_id
     *
     * @param contractId the value for finance.contract_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.finance_type
     *
     * @return the value of finance.finance_type
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.finance_name
     *
     * @return the value of finance.finance_name
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public String getFinanceName() {
        return financeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.finance_name
     *
     * @param financeName the value for finance.finance_name
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setFinanceName(String financeName) {
        this.financeName = financeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.money
     *
     * @return the value of finance.money
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.money
     *
     * @param money the value for finance.money
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.settleDate
     *
     * @return the value of finance.settleDate
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public Date getSettledate() {
        return settledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.settleDate
     *
     * @param settledate the value for finance.settleDate
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setSettledate(Date settledate) {
        this.settledate = settledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.remark
     *
     * @return the value of finance.remark
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.remark
     *
     * @param remark the value for finance.remark
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    public String getContractName() {
		return contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}
	
}