package com.web.model;


public class Material {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.material_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private Integer materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.contract_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.material_name
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private String materialName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.unit
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.amount
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.remark
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    private String remark;
    
    //非数据库字段
    private String contractName;

   

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.material_id
     *
     * @return the value of material.material_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.material_id
     *
     * @param materialId the value for material.material_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.contract_id
     *
     * @return the value of material.contract_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.contract_id
     *
     * @param contractId the value for material.contract_id
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.material_name
     *
     * @return the value of material.material_name
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.material_name
     *
     * @param materialName the value for material.material_name
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.unit
     *
     * @return the value of material.unit
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.unit
     *
     * @param unit the value for material.unit
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.amount
     *
     * @return the value of material.amount
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.amount
     *
     * @param amount the value for material.amount
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.remark
     *
     * @return the value of material.remark
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.remark
     *
     * @param remark the value for material.remark
     *
     * @mbg.generated Tue Apr 10 10:47:53 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    //非数据库字段
    public String getContractName() {
		return contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}
}