package com.web.model;


import java.util.Date;

public class ProjectProgress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.project_progress_id
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private Integer projectProgressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.address
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.name
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.persion_in_charge
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private String persionInCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.field_supervisor
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private String fieldSupervisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.process
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private String process;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.safety_quality
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private String safetyQuality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.reporting_date
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private Date reportingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_progress.remark
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.project_progress_id
     *
     * @return the value of project_progress.project_progress_id
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public Integer getProjectProgressId() {
        return projectProgressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.project_progress_id
     *
     * @param projectProgressId the value for project_progress.project_progress_id
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setProjectProgressId(Integer projectProgressId) {
        this.projectProgressId = projectProgressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.address
     *
     * @return the value of project_progress.address
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.address
     *
     * @param address the value for project_progress.address
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.name
     *
     * @return the value of project_progress.name
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.name
     *
     * @param name the value for project_progress.name
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.persion_in_charge
     *
     * @return the value of project_progress.persion_in_charge
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public String getPersionInCharge() {
        return persionInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.persion_in_charge
     *
     * @param persionInCharge the value for project_progress.persion_in_charge
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setPersionInCharge(String persionInCharge) {
        this.persionInCharge = persionInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.field_supervisor
     *
     * @return the value of project_progress.field_supervisor
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public String getFieldSupervisor() {
        return fieldSupervisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.field_supervisor
     *
     * @param fieldSupervisor the value for project_progress.field_supervisor
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setFieldSupervisor(String fieldSupervisor) {
        this.fieldSupervisor = fieldSupervisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.process
     *
     * @return the value of project_progress.process
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.process
     *
     * @param process the value for project_progress.process
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setProcess(String process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.safety_quality
     *
     * @return the value of project_progress.safety_quality
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public String getSafetyQuality() {
        return safetyQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.safety_quality
     *
     * @param safetyQuality the value for project_progress.safety_quality
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setSafetyQuality(String safetyQuality) {
        this.safetyQuality = safetyQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.reporting_date
     *
     * @return the value of project_progress.reporting_date
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public Date getReportingDate() {
        return reportingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.reporting_date
     *
     * @param reportingDate the value for project_progress.reporting_date
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setReportingDate(Date reportingDate) {
        this.reportingDate = reportingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_progress.remark
     *
     * @return the value of project_progress.remark
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_progress.remark
     *
     * @param remark the value for project_progress.remark
     *
     * @mbg.generated Sun Apr 08 15:57:06 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}